import { Stage, StageId } from './types';

export const STAGES: Stage[] = [
  {
    id: StageId.PRE_PREG,
    label: '備孕期',
    description: '科學計畫',
    keyFocus: '調整體質，養精蓄銳',
    icon: '🌱',
    topics: [
      { id: 'checkup', title: '孕前檢查要做哪些？', tag: '檢查', queryPrompt: '備孕夫妻必要的遺傳諮詢與健康檢查項目' },
      { id: 'age_limit', title: '幾歲算高齡產婦？', tag: '衛教', queryPrompt: '高齡產婦定義與懷孕風險評估' },
      { id: 'timing', title: '排卵期怎麼算最準？', tag: '衛教', queryPrompt: '科學計算排卵期與最佳受孕時機' },
      { id: 'lifestyle', title: '男生需要禁慾養精嗎？', tag: '衛教', queryPrompt: '備孕期間男性的精子品質與禁慾天數迷思' },
      { id: 'good_sperm', title: '養精食物有哪些？', tag: '營養', queryPrompt: '男性提升精子品質的食物與生活習慣' },
      { id: 'supplements', title: '備孕要吃什麼保健品？', tag: '營養', queryPrompt: '備孕期間男性與女性需要的營養補充品清單(葉酸, Q10, 精氨酸)' },
      { id: 'ivf_cost', title: '試管嬰兒要花多少錢？', tag: '商品', queryPrompt: '台灣試管嬰兒(IVF)療程費用與補助懶人包' },
      { id: 'ivf_decision', title: '我該做試管嬰兒嗎？', tag: '價值觀', queryPrompt: '試管嬰兒成功率與心理建設' },
    ]
  },
  {
    id: StageId.PREG_EARLY,
    label: '懷孕初期',
    subLabel: '0-3個月',
    description: '害喜地獄',
    keyFocus: '胚胎穩定，媽媽放鬆',
    icon: '🤢',
    topics: [
      { id: 'heartbeat', title: '幾週可以聽到心跳？', tag: '檢查', queryPrompt: '胎兒心跳出現週數與超音波檢查' },
      { id: 'nipt', title: 'NIPT跟羊穿哪個好？', tag: '檢查', queryPrompt: 'NIPT非侵入性檢測與羊膜穿刺優缺點比較' },
      { id: 'sma', title: 'SMA、脆折症要做嗎？', tag: '檢查', queryPrompt: '孕早期自費產檢項目SMA與脆折症必要性' },
      { id: 'bleeding', title: '初期出血正常嗎？', tag: '健康', queryPrompt: '懷孕初期出血的原因分辨與危險徵兆' },
      { id: 'morning_sickness', title: '孕吐太嚴重怎麼辦？', tag: '健康', queryPrompt: '緩解嚴重孕吐的科學方法與飲食建議' },
      { id: 'folic_acid', title: '葉酸要吃到何時？', tag: '營養', queryPrompt: '孕期葉酸補充劑量與截止時間' },
      { id: 'sex', title: '懷孕初期可以愛愛嗎？', tag: '衛教', queryPrompt: '懷孕前三個月性行為的安全性評估' },
      { id: 'anti_radiation', title: '防輻射衣有用嗎？', tag: '商品', queryPrompt: '孕婦防輻射衣的科學效用與電磁波迷思' },
    ]
  },
  {
    id: StageId.PREG_MID,
    label: '懷孕中期',
    subLabel: '4-6個月',
    description: '食慾大開',
    keyFocus: '體重控制，補充DHA',
    icon: '🤰',
    topics: [
      { id: '4d_ultrasound', title: '高層次超音波必做？', tag: '檢查', queryPrompt: '高層次超音波檢查項目與必要性' },
      { id: 'high_sugar', title: '喝糖水沒過怎麼辦？', tag: '檢查', queryPrompt: '妊娠糖尿病篩檢未通過的飲食控制' },
      { id: 'weight', title: '體重增加多少算正常？', tag: '檢查', queryPrompt: '孕期體重控制標準與對胎兒影響' },
      { id: 'movement', title: '何時會感覺到胎動？', tag: '健康', queryPrompt: '初產婦與經產婦胎動出現時間與頻率' },
      { id: 'constipation', title: '孕期便秘怎麼救？', tag: '健康', queryPrompt: '改善孕婦便秘的飲食與藥物使用安全' },
      { id: 'dha', title: '需要補DHA/魚油嗎？', tag: '營養', queryPrompt: '孕期DHA補充對胎兒腦部發展的效益與時機' },
      { id: 'pillow', title: '月亮枕值得買嗎？', tag: '商品', queryPrompt: '孕婦睡眠改善月亮枕推薦與使用心得' },
      { id: 'maternity_wear', title: '孕婦褲怎麼挑？', tag: '商品', queryPrompt: '舒適好穿的孕婦裝與托腹帶選購指南' },
    ]
  },
  {
    id: StageId.PREG_LATE,
    label: '懷孕後期',
    subLabel: '7-9個月',
    description: '準備卸貨',
    keyFocus: '注意產兆，準備待產包',
    icon: '🐘',
    topics: [
      { id: 'gbs', title: '乙型鏈球菌沒過怎辦？', tag: '檢查', queryPrompt: '乙型鏈球菌篩檢陽性對生產的影響與處置' },
      { id: 'position', title: '胎位不正一定要剖腹？', tag: '檢查', queryPrompt: '胎位不正的矯正運動與生產方式選擇' },
      { id: 'preeclampsia', title: '血壓高是子癲前症？', tag: '檢查', queryPrompt: '子癲前症血壓標準與尿蛋白檢測' },
      { id: 'contraction', title: '真假宮縮怎麼分？', tag: '健康', queryPrompt: '區分假性宮縮與真實產兆的判斷標準' },
      { id: 'swelling', title: '腳水腫很嚴重？', tag: '健康', queryPrompt: '生理性水腫與病理性水腫的差別' },
      { id: 'pain_relief', title: '無痛分娩真的不痛？', tag: '衛教', queryPrompt: '減痛分娩的施打時機與副作用' },
      { id: 'bag_prep', title: '待產包必備清單？', tag: '商品', queryPrompt: '生產待產包極簡清單與不必要的物品' },
      { id: 'confinement_money', title: '月子中心錢誰出？', tag: '價值觀', queryPrompt: '月子中心費用分擔的家庭價值觀討論' },
    ]
  },
  {
    id: StageId.NEWBORN_BIRTH,
    label: '坐月子期',
    subLabel: '0-1個月',
    description: '新手混亂',
    keyFocus: '母體恢復，建立哺乳',
    icon: '🤱',
    topics: [
      { id: 'jaundice_light', title: '黃疸退很慢要照光？', tag: '檢查', queryPrompt: '生理性與病理性黃疸指數標準與醫院照光標準' },
      { id: 'poop_color', title: '大便青綠色正常嗎？', tag: '健康', queryPrompt: '新生兒大便顏色色卡對照與健康警訊' },
      { id: 'weight_loss', title: '寶寶體重減輕脫水？', tag: '健康', queryPrompt: '新生兒生理性脫水幅度與恢復時間' },
      { id: 'baby_acne', title: '寶寶臉上長痘痘？', tag: '健康', queryPrompt: '新生兒脂漏性皮膚炎成因與清潔照護' },
      { id: 'umbilical', title: '臍帶掉落與護理？', tag: '衛教', queryPrompt: '新生兒臍帶護理消毒步驟與感染徵兆' },
      { id: 'lochia', title: '產後惡露要排多久？', tag: '健康', queryPrompt: '產後惡露顏色變化階段與異常出血判斷' },
      { id: 'breastmilk_supply', title: '奶水不足怎麼追奶？', tag: '營養', queryPrompt: '產後黃金追奶期與發奶食物科學' },
      { id: 'pump', title: '電動擠乳器推哪牌？', tag: '商品', queryPrompt: '電動擠乳器評比與免手持擠乳器優缺點' },
    ]
  },
  {
    id: StageId.NEWBORN_ROUTINE,
    label: '第四孕期',
    subLabel: '1-4個月',
    description: '適應世界',
    keyFocus: '睡眠儀式，腸絞痛對策',
    icon: '👶',
    topics: [
      { id: 'vaccine_fever', title: '打疫苗發燒怎麼辦？', tag: '檢查', queryPrompt: '嬰兒疫苗接種後發燒護理與就醫時機' },
      { id: 'spit_up', title: '喝完奶一直溢奶？', tag: '健康', queryPrompt: '生理性溢奶與病理性胃食道逆流分辨' },
      { id: 'crying_colic', title: '半夜無故大哭(腸絞痛)？', tag: '健康', queryPrompt: '嬰兒腸絞痛(Colic)的症狀判斷與安撫技巧5S' },
      { id: 'flat_head', title: '頭睡扁了怎麼辦？', tag: '發展', queryPrompt: '嬰兒頭型矯正黃金期與姿勢調整' },
      { id: 'tummy_time', title: '什麼時候練抬頭？', tag: '發展', queryPrompt: 'Tummy Time 趴臥練習的時機與安全' },
      { id: 'sleep_training', title: '可以訓練睡過夜嗎？', tag: '發展', queryPrompt: '新生兒睡眠模式與睡眠訓練的最早時機' },
      { id: 'vitamin_d', title: '寶寶要補維生素D嗎？', tag: '營養', queryPrompt: '純母乳寶寶與配方奶寶寶的維生素D補充建議' },
      { id: 'swaddle', title: '蝴蝶包巾有用嗎？', tag: '商品', queryPrompt: '新生兒包巾懶人包巾防驚嚇效果與安全性' },
    ]
  },
  {
    id: StageId.INFANT_FLIP,
    label: '翻身萌芽',
    subLabel: '4-6個月',
    description: '副食品戰場',
    keyFocus: '嘗試副食品，翻身安全',
    icon: '🥣',
    topics: [
      { id: 'growth_curve', title: '生長曲線掉下來怎辦？', tag: '檢查', queryPrompt: '嬰兒生長曲線百分位解讀與生長遲緩警訊' },
      { id: 'skin_allergy', title: '皮膚紅紅是異膚嗎？', tag: '健康', queryPrompt: '嬰兒異位性皮膚炎症狀與口水疹區別' },
      { id: 'solids_first', title: '第一口副食品吃啥？', tag: '營養', queryPrompt: '嬰兒副食品添加順序、過敏測試與傳統粥派vsBLW' },
      { id: 'allergy_food', title: '蛋黃/海鮮會過敏？', tag: '營養', queryPrompt: '延後給予高致敏食物是否能預防過敏的最新研究' },
      { id: 'milestone_flip', title: '還不會翻身正常嗎？', tag: '發展', queryPrompt: '嬰兒翻身發展里程碑與輔助練習' },
      { id: 'drooling', title: '一直流口水是長牙？', tag: '發展', queryPrompt: '嬰兒流口水原因與長牙前兆' },
      { id: 'high_chair', title: '餐椅推薦哪一張？', tag: '商品', queryPrompt: '好清潔穩固的嬰兒餐椅(High Chair)推薦比較' },
      { id: 'read_start', title: '什麼時候開始親子共讀？', tag: '教育', queryPrompt: '嬰兒親子共讀好處與黑白圖書/布書選擇' },
    ]
  },
  {
    id: StageId.INFANT_CRAWL,
    label: '爬行探索',
    subLabel: '7-12個月',
    description: '七坐八爬',
    keyFocus: '居家安全，分離焦慮',
    icon: '🧸',
    topics: [
      { id: 'flu_shot', title: '流感疫苗該不該打？', tag: '檢查', queryPrompt: '嬰幼兒流感疫苗安全性與副作用' },
      { id: 'teething_fever', title: '長牙會發燒嗎？', tag: '健康', queryPrompt: '長牙期的不適症狀與發燒迷思釐清' },
      { id: 'roseola', title: '燒退了出疹子？', tag: '健康', queryPrompt: '嬰兒玫瑰疹症狀病程與照護' },
      { id: 'water_drinking', title: '需要喝水嗎？喝多少？', tag: '營養', queryPrompt: '嬰兒開始喝水的時機點與腎臟負擔迷思' },
      { id: 'stranger_anxiety', title: '開始認生怕生怎麼辦？', tag: '心理', queryPrompt: '嬰兒分離焦慮與認生期的發展心理' },
      { id: 'milestone_sit_crawl', title: '還不會坐爬正常嗎？', tag: '發展', queryPrompt: '七坐八爬九發牙的發展時程與落後評估' },
      { id: 'playpen', title: '圍欄/地墊怎麼挑？', tag: '商品', queryPrompt: '嬰兒爬行地墊與圍欄安全性選購重點' },
      { id: 'no_screen', title: '這階段能看卡通嗎？', tag: '教育', queryPrompt: '一歲以下嬰兒避免螢幕接觸的腦部發展原因' },
    ]
  },
  {
    id: StageId.TODDLER_WALK,
    label: '學步探索',
    subLabel: '1歲-1歲半',
    description: '搖搖晃晃',
    keyFocus: '學走路，斷奶轉換',
    icon: '🐣',
    topics: [
      { id: 'walking_delay', title: '還不敢放手走正常嗎？', tag: '發展', queryPrompt: '幼兒學走路里程碑與發展遲緩警訊' },
      { id: 'shoes_walk', title: '學步鞋怎麼挑？', tag: '商品', queryPrompt: '幼兒學步鞋挑選重點與足部發展影響' },
      { id: 'weaning', title: '如何幫寶寶戒夜奶？', tag: '營養', queryPrompt: '一歲後漸進式斷奶與戒夜奶策略' },
      { id: 'cow_milk', title: '可以喝鮮奶了嗎？', tag: '營養', queryPrompt: '一歲後配方奶換鮮奶的銜接與營養比較' },
      { id: 'tantrum_start', title: '開始會丟東西打人？', tag: '教育', queryPrompt: '一歲兒情緒表達與攻擊行為引導' },
      { id: 'fluoride_varnish', title: '牙齒塗氟幾月一次？', tag: '檢查', queryPrompt: '幼兒塗氟頻率與補助規定' },
      { id: 'read_interact', title: '繪本都拿來啃怎麼辦？', tag: '教育', queryPrompt: '一歲寶寶共讀技巧與硬頁書選擇' },
      { id: 'sleep_regress', title: '睡眠倒退嚕怎辦？', tag: '健康', queryPrompt: '一歲睡眠倒退期原因與作息調整' },
    ]
  },
  {
    id: StageId.TODDLER_TALK,
    label: '幼兒爆發',
    subLabel: '1歲半-3歲',
    description: '語言爆發',
    keyFocus: '規矩建立，戒尿布',
    icon: '🦖',
    topics: [
      { id: 'language_delay', title: '不愛說話是遲緩嗎？', tag: '檢查', queryPrompt: '幼兒語言發展里程碑與語言遲緩評估界線' },
      { id: 'potty_train', title: '何時開始戒尿布？', tag: '發展', queryPrompt: '如廁訓練的生理與心理準備完成訊號' },
      { id: 'tantrum_big', title: '崩潰躺地大叫怎麼教？', tag: '教育', queryPrompt: '兩歲兒(Terrible Two)情緒調節與父母應對策略' },
      { id: 'picky_eater', title: '不吃菜挑食怎麼辦？', tag: '營養', queryPrompt: '幼兒挑食原因與營造快樂餐桌的方法' },
      { id: 'push_bike', title: '滑步車值得買嗎？', tag: '商品', queryPrompt: '幼兒滑步車(Push Bike)對平衡感發展的幫助' },
      { id: 'screen_time', title: '可以看電視手機嗎？', tag: '衛教', queryPrompt: '幼兒螢幕時間規範與藍光對視力大腦影響' },
      { id: 'kindergarten', title: '幾歲送幼兒園比較好？', tag: '教育', queryPrompt: '幼兒園入學年齡與分離焦慮準備' },
      { id: 'sharing', title: '不願意分享玩具？', tag: '教育', queryPrompt: '幼兒物權觀念發展與分享行為引導' },
    ]
  }
];